name: Deploy

on:
  push:
    branches: [ main ]

env:
  AWS_REGION: us-west-2
  TERRAFORM_VERSION: 1.5.7

jobs:
  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    environment: production

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Install dependencies
      run: go mod download

    - name: Build Lambda function
      run: |
        GOOS=linux GOARCH=amd64 go build -o main ./cmd/lambda
        zip lambda.zip main

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}

    - name: Terraform Init
      run: |
        cd terraform
        terraform init

    - name: Terraform Plan
      run: |
        cd terraform
        terraform plan -var="db_password=${{ secrets.DB_PASSWORD }}"

    - name: Terraform Apply
      run: |
        cd terraform
        terraform apply -auto-approve -var="db_password=${{ secrets.DB_PASSWORD }}"

    - name: Upload Lambda function
      run: |
        aws lambda update-function-code \
          --function-name tree-api-api \
          --zip-file fileb://lambda.zip 